image: node:8.12.0

stages:
  - install
  - build
  # - test
  # - lint
  # - code_formatting
  # - docker


install:
  step: install
  script:
   - npm install --no-save

build:
  step: build
  script:
   - npm run build
