image: node:8.12.0

stages:
  - install
  - build
  # - test
  # - lint
  # - code_formatting
  # - docker

install:
  stage: install
  artifacts:
    paths:
      - node_modules
      - services/ai/node_modules
      - services/bootstrap/node_modules
      - services/database/node_modules
      - services/location/node_modules
    expire_in: 1 day
  script:
   - npm install --no-save --unsafe-perm

build:
  stage: build
  script:
   - npm run build
