# See https://docs.gitlab.com/ee/ci/yaml/README.html

image: node:12

services:
  - docker:dind

stages:
  - install
  - build
  - lint
  - code_formatting
  - docker

install:
  stage: install
  artifacts:
    paths:
      - node_modules
      - services/ais/node_modules
      - services/bootstrap/node_modules
      - services/database/node_modules
      - services/location/node_modules
    expire_in: 1 day
  script:
    - npm install --no-save --unsafe-perm

code_formatting:
  stage: code_formatting
  script:
    - npm run prettier:check

build:
  stage: build
  artifacts:
    paths:
      - dist
    expire_in: 1 day
  script:
    - npm run build

lint:
  stage: lint
  allow_failure: true
  script:
    - npm run lint

docker_build_only:
  stage: docker
  image: docker:stable
  needs:
    - job: build
  except:
    - develop
    - release
  script:
    - docker build -t $CI_REGISTRY/civilmrcc/onefleet/app:development .
    - docker build -t $CI_REGISTRY/civilmrcc/onefleet/services:development services

docker_build_and_push_development:
  stage: docker
  image: docker:stable
  environment:
    name: development
  needs:
    - job: build
      artifacts: true
  only:
    - develop
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY/civilmrcc/onefleet/app:development .
    - docker build -t $CI_REGISTRY/civilmrcc/onefleet/services:development services
    - docker push $CI_REGISTRY/civilmrcc/onefleet/app:development
    - docker push $CI_REGISTRY/civilmrcc/onefleet/services:development
    - docker logout $CI_REGISTRY

docker_build_and_push_production:
  stage: docker
  image: docker:stable
  environment:
    name: production
  needs:
    - job: build
      artifacts: true
  only:
    - release
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY/civilmrcc/onefleet/app:production .
    - docker build -t $CI_REGISTRY/civilmrcc/onefleet/services:production services
    - docker push $CI_REGISTRY/civilmrcc/onefleet/app:production
    - docker push $CI_REGISTRY/civilmrcc/onefleet/services:production
    - docker logout $CI_REGISTRY

include:
  - template: Dependency-Scanning.gitlab-ci.yml