# See https://docs.gitlab.com/ee/ci/yaml/README.html

image: node:12

services:
  - docker:dind

stages:
  - install
  - build
  - lint
  - code_formatting
  - docker

install:
  stage: install
  artifacts:
    paths:
      - node_modules
      - services/ais/node_modules
      - services/bootstrap/node_modules
      - services/database/node_modules
      - services/location/node_modules
    expire_in: 1 day
  script:
    - npm install --no-save --unsafe-perm

code_formatting:
  stage: code_formatting
  allow_failure: true
  script:
    - npm run prettier:check

build:
  stage: build
  artifacts:
    paths:
      - dist
    expire_in: 1 day
  script:
    - npm run build

lint:
  stage: lint
  allow_failure: true
  script:
    - npm run lint

docker-app:
  stage: docker
  image: docker:stable
  allow_failure: true
  only:
    - master
  script:
    - docker build -t $CI_REGISTRY/civilmrcc/onefleet/app .
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $CI_REGISTRY/civilmrcc/onefleet/app
    - docker logout $CI_REGISTRY

docker-services:
  stage: docker
  image: docker:stable
  allow_failure: true
  only:
    - master
  script:
    - docker build -t $CI_REGISTRY/civilmrcc/onefleet/services services
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $CI_REGISTRY/civilmrcc/onefleet/services
    - docker logout $CI_REGISTRY
