# image: node:8.12.0
# image: centigrade/gitlab-ci-node-angular
image: docker:19.03.1

services:
  - docker:dind

stages:
  - install
  - build
  - lint
  - docker
  # - test
  # - code_formatting

install:
  stage: install
  artifacts:
    paths:
      - node_modules
      - services/ais/node_modules
      - services/bootstrap/node_modules
      - services/database/node_modules
      - services/location/node_modules
    expire_in: 1 day
  script:
    - npm install --no-save --unsafe-perm

# build:
#   stage: build
#   artifacts:
#     paths:
#       - dist
#     expire_in: 1 day
#   script:
#     - npm run build

# lint:
#   stage: lint
#   allow_failure: true
#   script:
#     - npm run lint

docker-ais:
  stage: docker
  allow_failure: true
  script:
    # create image
    - cd services/ais
    - docker build -t onefleet/ais .

    # push image
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    # TODO check gitlab permissions to push to registry
    # - docker push onefleet/ais
