# See https://docs.gitlab.com/ee/ci/yaml/README.html

image: node:8.12.0

services:
  - docker:dind

stages:
  - install
  - build
  - lint
  - code_formatting
  - docker
  # - test
  # - code_formatting

install:
  stage: install
  artifacts:
    paths:
      - node_modules
      - services/ais/node_modules
      - services/bootstrap/node_modules
      - services/database/node_modules
      - services/location/node_modules
    expire_in: 1 day
  script:
    - npm install --no-save --unsafe-perm

code_formatting:
  stage: code_formatting
  allow_failure: true
  script:
    - npm run prettier:check

build:
  stage: build
  artifacts:
    paths:
      - dist
    expire_in: 1 day
  script:
    - npm run build

lint:
  stage: lint
  allow_failure: true
  script:
    - npm run lint

variables:
  IMAGE_NAME: $CI_REGISTRY/niczem/onefleet/master

docker-app:
  stage: docker
  image: docker:stable
  allow_failure: true
  only:
    - master
  script:
    - docker build -t $IMAGE_NAME .
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $IMAGE_NAME
    - docker logout $CI_REGISTRY
