version: '3.7'

services:
  app:
    container_name: onefleet.app
    image: registry.gitlab.com/civilmrcc/onefleet/app:development
    labels:
      - 'com.centurylinklabs.watchtower.enable=true'
    ports:
      - '8080:80'

  database:
    image: scttmthsn/pouchdb-server
    container_name: onefleet.database
    labels:
      - 'com.centurylinklabs.watchtower.enable=false'
    ports:
      - 5984:5984
    volumes:
      # NOTE: Mounted volumes do not work on windows. As a workaround disable the next line and uncomment the two other lines
      - ./services/database/docker_mount:/pouchdb/
      # - type: volume
      #   target: /pouchdb

  ais:
    container_name: onefleet.ais
    image: registry.gitlab.com/civilmrcc/onefleet/services:development
    labels:
      - 'com.centurylinklabs.watchtower.enable=true'
    command: node ais/main.js
    ports:
      - 5000:5000

  location:
    container_name: onefleet.location
    image: registry.gitlab.com/civilmrcc/onefleet/services:development
    labels:
      - 'com.centurylinklabs.watchtower.enable=true'
    command: node location/main.js -t 15
    env_file:
      - .env
    environment:
      - AIS_API=http://ais:5000
      - DB_URL=http://database:5984

  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    environment:
      - WATCHTOWER_LABEL_ENABLE=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
