<template>
	<div id="loadingscreen">
		<img src="@/assets/paper-boat.svg" alt="" id="paperboat">
		<p>loading</p>
		<div class="thingy"></div>
	</div>
</template>
<script lang="ts">
export default {
  name: 'Loadingscreen',
};
</script>
<style>
#loadingscreen{
  position:fixed;
  background:#17AFFA;
  z-index: 1001;
  top:0;
  right:0;
  bottom:0;
  left:0;
  color:#FFF;
}

#paperboat{
	-webkit-filter: invert(1);
	filter: invert(1);
	width:20vw;
	left:40vw;
	top:10vw;
	position:absolute;



	-webkit-animation: vibrate-1 0.3s linear infinite both;
			animation: vibrate-1 0.3s linear infinite both;
}


/* ----------------------------------------------
 * Generated by Animista on 2020-5-8 5:20:52
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation vibrate-1
 * ----------------------------------------
 */
@-webkit-keyframes vibrate-1 {
  0% {
	-webkit-transform: translate(0);
			transform: translate(0);
  }
  20% {
	-webkit-transform: translate(-2px, 2px);
			transform: translate(-2px, 2px);
  }
  40% {
	-webkit-transform: translate(-2px, -2px);
			transform: translate(-2px, -2px);
  }
  60% {
	-webkit-transform: translate(2px, 2px);
			transform: translate(2px, 2px);
  }
  80% {
	-webkit-transform: translate(2px, -2px);
			transform: translate(2px, -2px);
  }
  100% {
	-webkit-transform: translate(0);
			transform: translate(0);
  }
}

p{
	position:absolute;

	bottom:0;
	width:200px;
	left:50%;
	margin-left:-100px;
	text-align:center;
}
</style>
